### ISSUE TITLE
RuntimeError: get_voronoi_nodes requires Zeo++ cython extension to be installed. Please contact developers of Zeo++ to obtain it.

### ISSUE THREAD

**Issue by feacluster** [learningmatter-mit/VOID#9]
I was able to successfully install VOID in my home directory and run the examples. I next tried installing it in a shared folder so that other users can run it without me having to install it for them one by one. However, this is the error other users get when trying to run my installation in the shared folder. The strange thing is I am able to run the example using the shared folder installation. Guessing some permissions issue, but not sure how to narrow it down:

```
(VOID) [user@loginnode test]$ dock.py {AFI.cif,molecule.xyz} -o ~/Desktop/docked -d batch -s voronoi_cluster -f min_distance
Traceback (most recent call last):
  File "/gpfs/scratch/myapps/void/software/miniconda/envs/VOID/bin/dock.py", line 23, in <module>
    complexes = docker.dock(args.attempts)
  File "/gpfs/scratch/myapps/void/software/miniconda/envs/VOID/lib/python3.6/site-packages/VOID/dockers/base.py", line 66, in dock
    for point in self.sampler.get_points(self.host):
  File "/gpfs/scratch/myapps/void/software/miniconda/envs/VOID/lib/python3.6/site-packages/VOID/samplers/voronoi.py", line 154, in get_points
    nodes = self.get_voronoi_nodes(structure)
  File "/gpfs/scratch/myapps/void/software/miniconda/envs/VOID/lib/python3.6/site-packages/VOID/samplers/voronoi.py", line 114, in get_voronoi_nodes
    nodes, _, _ = self.get_voronoi_structures()
  File "/gpfs/scratch/myapps/void/software/miniconda/envs/VOID/lib/python3.6/site-packages/VOID/samplers/voronoi.py", line 72, in get_voronoi_structures
    self._structure, radii, probe_rad=self.probe_radius
  File "/gpfs/scratch/myapps/void/software/miniconda/envs/VOID/lib/python3.6/site-packages/monty/dev.py", line 96, in decorated
    raise RuntimeError(self.message)
RuntimeError: get_voronoi_nodes requires Zeo++ cython extension to be installed. Please contact developers of Zeo++ to obtain it.
```

**Comment by mohan-s1** [comment]
Hi, 

I'm not sure if the VOID software is an avenue you're still pursuing, but some people from the University of Virginia successfully containerized it using Docker. A link can be found [here](https://github.com/digital-synthesis-lab/VOID?tab=readme-ov-file#installation-and-usage-via-docker). The code runs quite fast locally, but you may have to switch container platforms from Docker to Apptainer should you wish to run it on a computing cluster. I hope this helps!

https://github.com/digital-synthesis-lab/VOID?tab=readme-ov-file#installation-and-usage-via-docker
